#!/usr/bin/env bash
# setup-env.sh — interactively create (or update) .env.local for this demo.
# Prompts for each variable; secrets are read hidden and never echoed. Existing
# values are offered as defaults (press Enter to keep). Writes .env.local with
# 600 perms — the notebook and scripts source it automatically.
#
#   ./scripts/setup-env.sh

set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENVFILE="$LAB_ROOT/.env.local"

# Preload existing values so we can offer them as defaults.
if [ -f "$ENVFILE" ]; then set -a; . "$ENVFILE"; set +a; fi

# ask VAR "prompt" ["default"] — visible input, keeps current/default on Enter.
ask() {
  local var="$1" prompt="$2" def="${3:-}" cur ans
  cur="$(eval "printf '%s' \"\${$var:-}\"")"; [ -n "$cur" ] || cur="$def"
  read -r -p "  $prompt${cur:+ [$cur]}: " ans
  printf -v "$var" '%s' "${ans:-$cur}"
}

# ask_secret VAR "prompt" — hidden input; shows only whether a value is set.
ask_secret() {
  local var="$1" prompt="$2" cur ans
  cur="$(eval "printf '%s' \"\${$var:-}\"")"
  read -r -s -p "  $prompt${cur:+ [set — Enter to keep]}: " ans; echo
  if [ -n "$ans" ]; then printf -v "$var" '%s' "$ans"; else printf -v "$var" '%s' "$cur"; fi
}

echo "Setting up $ENVFILE"
echo
echo "Required for the local kagent path:"
ask_secret ANTHROPIC_API_KEY "Anthropic API key (sk-ant-...)"
ask_secret SOLO_LICENSE_KEY  "Solo Enterprise for kagent license key"
echo
echo "Only for the AWS Bedrock AgentCore add-on (leave blank to skip):"
ask AWS_PROFILE "AWS CLI profile (SSO-backed)"
ask AWS_REGION  "AWS region" "${AWS_REGION:-us-east-1}"

umask 077
cat > "$ENVFILE" <<EOF
# Generated by scripts/setup-env.sh — gitignored, do not commit.
export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
export SOLO_LICENSE_KEY="${SOLO_LICENSE_KEY:-}"
export AWS_PROFILE="${AWS_PROFILE:-}"
export AWS_REGION="${AWS_REGION:-us-east-1}"
EOF
chmod 600 "$ENVFILE"

echo
echo "Wrote $ENVFILE (600). Values (masked):"
mask() { if [ -n "${1:-}" ]; then echo "set (${#1} chars)"; else echo "MISSING"; fi; }
echo "  ANTHROPIC_API_KEY : $(mask "${ANTHROPIC_API_KEY:-}")"
echo "  SOLO_LICENSE_KEY  : $(mask "${SOLO_LICENSE_KEY:-}")"
echo "  AWS_PROFILE       : ${AWS_PROFILE:-<unset> (AgentCore add-on only)}"
echo "  AWS_REGION        : ${AWS_REGION:-us-east-1}"
echo
echo "Next: open demo.ipynb and run the Setup cell, or  ./scripts/quick.sh up"
